#pragma config(Sensor, S3,     BWSensor,       sensorLightActive)
#pragma config(Motor,  motorB,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(NXT)

long nLastXmitTimeStamp = nPgmTime;
long nDeltaTime         = 0;

const int kMaxSizeOfMessage = 30;
const int INBOX = 5;

void volg_lijn(){

		if (SensorValue(BWSensor) < 45) {
			motor[motorC] = 0;
			motor[motorB] = 30;
		}
		else {
			motor[motorC] = 30;
			motor[motorB] = 0;
		}

	motor[motorC] = 0;
	motor[motorB] = 0;

}


void sound_repeat() {

		playSound(soundBlip);

	return;
}

task main()
{
  TFileIOResult nBTCmdRdErrorStatus;
  int nSizeOfMessage;
  ubyte nRcvBuffer[kMaxSizeOfMessage];

  string s;

  while (true)
  {

    nSizeOfMessage = cCmdMessageGetSize(INBOX);

    if (nSizeOfMessage > kMaxSizeOfMessage)
      nSizeOfMessage = kMaxSizeOfMessage;
    if (nSizeOfMessage > 0){
    	nBTCmdRdErrorStatus = cCmdMessageRead(nRcvBuffer, nSizeOfMessage, INBOX);
    	nRcvBuffer[nSizeOfMessage] = '\0';
    	s = "";
    	stringFromChars(s, (char *) nRcvBuffer);
    	displayCenteredBigTextLine(4, s);
    	if(s == "UP"){
    		motor[LeftMotor] = 50;
    		motor[RightMotor] = 50;
    	}
    	if(s == "DOWN"){
    		motor[LeftMotor] = -50;
    		motor[RightMotor] = -50;

    	}
    	if(s == "LEFT"){
    		motor[LeftMotor] = -23;
    		motor[RightMotor] = 23;
    		wait1Msec(800);
    		s = "C";
    	}
    	if(s == "RIGHT"){
    		motor[LeftMotor] = 23;
    		motor[RightMotor] = -23;
    		wait1Msec(800);
    		s = "C";
    	}
    	if(s == "C" ) {
    	  motor[LeftMotor] = 0;
    		motor[RightMotor] = 0;
        }
        if(s == "A"){
       		 volg_lijn();
			}
    }
      if(motor[motorC] || motor[motorB]){
      	sound_repeat();
      }
    wait1Msec(100);
  }
  return;
}
