#pragma config(Sensor, S2,     ColorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S3,     sensorLeft,     sensorLightActive)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// stating that some functions exist and making a constant variable for the speed.
void forward(int speed);
void RGBValue(string sColor);
void searchLine(int speed, string sColor);
const int speed = 10;

void RGBValue(string &sColor) {
	  while (true) {
	    switch (SensorValue[ColorSensor])
	    {
	      case BLACKCOLOR:    sColor = "Black";     return;
	      case BLUECOLOR:     sColor = "Blue";      return;
	      case GREENCOLOR:    sColor = "Green";     return;
	      case YELLOWCOLOR:   sColor = "Yellow";    return;
	      case REDCOLOR:      sColor = "Red";       return;
	      case WHITECOLOR:    sColor = "White";     return;
	      default:            sColor = "???";       return;
			}
		}
}

// function to drive the robot forwards, only gets called if he only detects non black light.
void forward (int speed) {
	motor[motorRight] = speed;
	motor[motorLeft] = speed;
	return;
}

// function to go left or right depending on which of the 2 sensor detects a black line.
void searchLine(int speed, string sColor) {
	while (true) {
		RGBValue(sColor);
		if 	(SensorValue(sensorLeft) <= 45){
			motor[motorRight] = 40;
		}
		if (sColor == "Black"){
			motor[motorLeft] = 40;
		}
		if (SensorValue(sensorLeft) > 45 && (sColor != "Black")) {
			return;
		}
	}
}

task main()
{
	bool stop = false;
	string sColor;
	while (true) {
		if (stop == false) {
			forward(speed);
			RGBValue(sColor);
			if (SensorValue(sensorLeft) <= 45 || sColor == "Black")
				searchLine(speed, sColor);
			if (motor[motorLeft] || motor[motorRight])
				playSound(soundBlip);
		}
	}
}
