#pragma config(Sensor, S2,     ColorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S3,     BlackWhiteSensor, sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
string sColor;

  while (true) {
    switch (SensorValue[ColorSensor])
    {
      case BLACKCOLOR:    sColor = "Black";     break;
      case BLUECOLOR:     sColor = "Blue";      break;
      case GREENCOLOR:    sColor = "Green";     break;
      case YELLOWCOLOR:   sColor = "Yellow";    break;
      case REDCOLOR:      sColor = "Red";       break;
      case WHITECOLOR:    sColor = "White";     break;
      default:            sColor = "???";       break;
    }
    nxtDisplayCenteredTextLine(1, sColor);
    nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[BlackWhiteSensor]);
    wait1Msec(50);
    }
}
