#pragma config(Sensor, S3,     BWSensor,       sensorLightActive)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void forward(int speed); 	// function declaration of function forward and searchLine
void searchLine(int speed);
const int speed = 30;		// set variable speed to: 30

										
void forward (int speed) {		// function forward with parameter: "int speed"	
	motor[motorRight] = speed; 	// make motor C speed: 30 
	motor[motorLeft] = speed;	// make motor B speed: 30
	return;
}


void searchLine(int speed) {			//function searchLine with parameter: "int speed"
		stopAllMotors();		// call upon function stopAllMotors
		motor[motorRight] = speed; 	// set motorRight to speed: 30
		wait(1, seconds);		// wait 1 second
	
		while (true) {		
			if (SensorValue(BWSensor) > 45) {	// if Value picked up by the sensor is higher than 45
				stopAllMotors();		// set all motors speed to: 0
				motor[motorLeft] = 30; 		// set motorLeft to speed: 30
				wait(2, seconds);		// wait two seconds
				break;				// break the while loop
			}
		}
		return;
}

task main()
{
	while (true) {
									
		if (SensorValue(BWSensor) <= 45)	// if the picked up SensorValue is equal or less than 45
			forward(speed);                 // cal upon function: "forward" 
		else
			searchLine(speed);              // call upon function "searchLine"
	}
}
