#pragma config(Sensor, S3,     BWSensor,       sensorLightActive)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void forward(int speed);
void searchLine(int speed);
const int speed = 30;

void forward (int speed) {
	motor[motorRight] = speed;
	motor[motorLeft] = speed;
	return;
}

void searchLine(int speed) {
		stopAllMotors();
		motor[motorRight] = speed;
		wait(1, seconds);
		while (true) {
			if (SensorValue(BWSensor) > 45) {
				stopAllMotors();
				motor[motorLeft] = 30;
				wait(2, seconds);
				break;
			}
		}
		return;
}

task main()
{
	while (true) {
		if (SensorValue(BWSensor) <= 45)
			forward(speed);
		else
			searchLine(speed);
	}
}
